version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - VOICEFLOW_API_URL=${VOICEFLOW_API_URL}
      - VOICEFLOW_API_KEY=${VOICEFLOW_API_KEY}
      - VOICEFLOW_PROJECT_ID=${VOICEFLOW_PROJECT_ID}
      - VOICEFLOW_VERSION_ID=${VOICEFLOW_VERSION_ID}
      - RESET_STATE=${RESET_STATE}
      - BASE_URL=${BASE_URL}
      - BASE_PUBLIC_URL=${BASE_PUBLIC_URL}